image_path: "./data/images/2.png" # path to the input image

screen_text: " " # texts, describing the edit layer
comp_text: " " # texts, describing the full edited image
src_text: "bread" # texts, describing the input image

bootstrap_text: "bread" # text, describing the region of interest in the input image
bootstrap_epoch: 100 # number of epochs for bootstrapping (it is annealed during training)