image_path: "" # path to the input image

screen_text: "golden cat" # texts, describing the edit layer
comp_text: "golden cat" # texts, describing the full edited image
src_text: "cat" # texts, describing the input image

bootstrap_text: "cat" # text, describing the region of interest in the input image
bootstrap_epoch: 100 # number of epochs for bootstrapping (it is annealed during training)